---
- name: installing services
  hosts: Prod
  vars:
    PACKAGES:
      - httpd
      - nfs-utils
  tasks:
    - name: install the latest version of Apache
      yum:
        name: "{{ item }}"
        state: latest
      loop: "{{ PACKAGES }}"    
